name: Workflow for employee registration project demo

on:
  push:
    branches: [main]

jobs:
  build_artifact:
    runs-on: self-hosted
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: setting up java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Build Maven Application
        run: mvn clean package -DskipTests
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-war-${{ github.sha }}
          path: target/*.war
          retention-days: 1

  test:
    runs-on: self-hosted
    needs: build_artifact
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: setting up java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Run tests
        run: mvn test

  deployment:
    runs-on: self-hosted
    on:
      push:
        branches: [main]
    needs: [build_artifact, test]
    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: maven-war-${{ github.sha }}
          path: app

      - name: Deploy to Tomcat
        run: |
          ls -lh app/*.war
          sudo cp app/*.war /var/lib/tomcat10/webapps/
          sudo systemctl restart tomcat10
